databases:
  - name: pronet-db
    databaseName: pronet
    user: pronet
    plan: free
    region: frankfurt

services:
  - type: web
    name: pronet-api
    runtime: node
    plan: free
    region: frankfurt
    rootDir: api
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pronet-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        sync: false
